---
name: "Node.js CI"

on:
  push:
    branches: [ "main" ]

jobs:
  demo:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        test-env: [ "node", "jsdom" ]
    steps:
      - uses: "textbook/take-action@nodejs"
        with:
          node-version: "18.18.2"
      - run: "npm test -- --testEnvironment=${{ matrix.test-env }}"
        env:
          FORCE_COLOR: "true"
