---
name: "Node.js CI"

on:
  push:
    branches: [ "main" ]

jobs:
  demo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "textbook/take-action@nodejs"
        with:
          node-version: "18.18.2"
      - run: "npm test"
        env:
          FORCE_COLOR: "true"
